C:\Users\Test3\Desktop\automation\rms>test-case_pywinauto2.py
Traceback (most recent call last):
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\pywinauto\application.py", line 250, in __resolve_control
    ctrl = wait_until_passes(
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Test3\Desktop\automation\rms\test-case_pywinauto2.py", line 183, in <module>
    main()
  File "C:\Users\Test3\Desktop\automation\rms\test-case_pywinauto2.py", line 178, in main
    exit_app(app)
  File "C:\Users\Test3\Desktop\automation\rms\test-case_pywinauto2.py", line 153, in exit_app
    dlg.close()
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\pywinauto\application.py", line 396, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\pywinauto\application.py", line 203, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'title_re': '.*NCDEX RISK MANAGEMENT SYSTEM.*', 'backend': 'uia', 'process': 12968}
